from pathlib import Path
import json,re,zipfile,html
R=Path(__file__).resolve().parent
root=R/'fantasy-jobs'
items=[('warrior','100301','bsk_sw_1_01','战士 · Berserker','重甲、兽皮与大斧，偏力量型的奇幻战士。立绘使用斧，已保存的战斗动画是剑武器版本。'),('mage','130301','wrk_wa_1_01','法师 · Warlock','大檐魔法帽、紫色法袍和法杖，职业轮廓明确。'),('assassin','260201','asa_kn_1_01','刺客 · Assassin','匕首、暗色披肩与轻装，是同一系列的敏捷职业。')]
css='''*{box-sizing:border-box}body{margin:0;background:#11151e;color:#e8edf5;font:16px/1.8 system-ui,"Microsoft YaHei",sans-serif}header,main,footer{max-width:1180px;margin:auto;padding:28px}a{color:#b9d6ff}h1{font-size:38px}h2{font-size:29px}.note{padding:18px 22px;background:#263044;border-left:3px solid #d4b984;border-radius:6px}.nav{display:flex;gap:24px;flex-wrap:wrap;margin:22px 0}.card{border:1px solid #354155;background:#1c2432;border-radius:18px;overflow:hidden;margin:30px 0;display:grid;grid-template-columns:43% 57%}.portrait{width:100%;height:620px;object-fit:contain;background:radial-gradient(ellipse at center,#3e4455,#1a2130);padding:12px}.body{padding:26px}.small{font-size:14px;color:#aebbd1}.tag{color:#d4bf92;letter-spacing:1px}.button{display:inline-block;background:#b4d6d2;color:#192827;border-radius:8px;padding:10px 16px;text-decoration:none;margin:10px 10px 10px 0}.sheet{max-width:100%;max-height:400px;object-fit:contain;background:#313846}summary{cursor:pointer}footer{color:#aebbd1}@media(max-width:750px){.card{grid-template-columns:1fr}.portrait{height:500px}h1{font-size:29px}header,main{padding:18px}}'''
page='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>日系奇幻 · 战士 / 法师 / 刺客</title><style>'+css+'</style></head><body><header><a href="index.html?view=all">← 原素材库</a> · <a href="anime-learning-downloads.html">Live2D 学习模型</a><p class="tag">FANTASY JOBS / NON-PIXEL / DJEETA</p><h1>日系奇幻 · 战士、法师、刺客</h1><p>这次是同一游戏《碧蓝幻想》中女主 Djeeta 的三种职业形态，非像素日系画风。每种职业单独存放，并保存对应战斗动画资料。</p><div class="note"><b>游戏原素材研究资料，不是授权免费素材包。</b>版权归 Cygames 或其许可方；公开下载不等于获得使用授权，也不能仅凭非商用就推定可任意使用。本页按你的个人学习目的整理，独立于之前的可商用素材库。已保存的图片和动画描述可下载，但不是导入即用的完整游戏工程。</div><nav class="nav"><a href="#warrior">01 战士</a><a href="#mage">02 法师</a><a href="#assassin">03 刺客</a></nav></header><main>'
for slug,id,code,title,desc in items:
 p=root/slug;rel='fantasy-jobs/'+slug+'/'
 source='https://mizagbf.github.io/GBFAL/?id='+id
 player='https://mizagbf.github.io/GBFAP/?id='+id
 animation=(p/'animation.js').read_text();match=re.search(r'\{wait:5,setup:10[^}]+\}',animation);labels=match[0] if match else ''
 readme=f'''{title} / Djeeta / Granblue Fantasy\n\n来源索引：{source}\n动画播放器：{player}\n女性版本：Djeeta / {code}\n采集日期：2026-09-28\n\n角色版权归 Cygames, Inc. 或其许可方。不是开放许可素材，非商用不等于任意使用授权。本地整理用于个人资料研究。\n\n内容：立绘 portrait.png；原始身体和头部纹理；公共 weapon.png；animation.js 和 manifest.js。\n精灵图包含拆分部件，并非完整人物逐帧排列。动画文件采用游戏的 CreateJS 时间轴结构，不是 Spine 或 Live2D。\n本包不含播放器、游戏运行环境、全部技能特效与实际装备替换资源，不能直接当作完整动作工程运行。\n动画文件已核对待机、攻击、技能、召唤、胜利、受伤、死亡等入口；尚未逐项播放验证。多个 mortal_* 是时间轴入口，不应据此认定有同样数量的独立技能。\n\n预览方式：打开上方动画播放器，选择 Djeeta 女性版本。F 单帧前进，Shift+D 保存当前画布 PNG，W 打开录像设置。\n\n动画入口原文：\n{labels}\n'''
 (p/'README.txt').write_text(readme,encoding='utf-8')
 urls={'portrait.png':'img/sp/assets/leader/my/'+id+'_'+('sw' if slug=='warrior' else 'wa' if slug=='mage' else 'kn')+'_1_01.png',code+'.png':'img/sp/cjs/'+code+'.png',code+'_head.png':'img/sp/cjs/'+code+'_head.png','weapon.png':'img/sp/cjs/weapon.png','animation.js':'js/cjs/'+code+'.js','manifest.js':'js/model/manifest/'+code+'.js'}
 (p/'sources.json').write_text(json.dumps({k:'https://prd-game-a-granbluefantasy.akamaized.net/assets_en/'+v for k,v in urls.items()},indent=2),encoding='utf-8')
 with zipfile.ZipFile(p/(slug+'-research.zip'),'w',zipfile.ZIP_DEFLATED) as z:
  for n in [*urls,'README.txt','sources.json']:z.write(p/n,n)
 size=(p/(slug+'-research.zip')).stat().st_size/1024
 page+=f'''<article class="card" id="{slug}"><img class="portrait" src="{rel}portrait.png" alt="{title}女性职业立绘"><div class="body"><p class="tag">DJЕETA / 职业 {id}</p><h2>{title}</h2><p>{desc}</p><p><b>战斗部分是 Q 版角色。</b>左图为角色立绘；下方可展开真实战斗纹理，避免把立绘误当成动作帧。</p><p><b>已核对动画入口：</b>待机、攻击、技能、召唤、胜利、受伤、死亡等。已保存动画描述文件，未逐项播放验证。</p><a class="button" href="{rel}{slug}-research.zip" download>下载独立研究包 · {size:.0f} KB</a><a class="button" href="{player}" target="_blank" rel="noopener">打开战斗动画播放器 ↗</a><p class="small">播放器中选择 <b>Djeeta</b>，不要选 Gran（男性版本）。在线播放依赖外部服务。</p><p><a href="{source}" target="_blank" rel="noopener">全部职业图片来源 ↗</a> · <a href="{rel}README.txt">包内说明</a></p><details><summary>查看真实战斗精灵图（拆分部件）</summary><a href="{rel}{code}.png"><img class="sheet" src="{rel}{code}.png" alt="身体动作与部件纹理"></a><a href="{rel}{code}_head.png"><img class="sheet" src="{rel}{code}_head.png" alt="头部纹理"></a><p class="small">需要时间轴组合成完整人物。本地 ZIP 不是已导出的 PNG 连续帧包。</p></details></div></article>'''
page+='''<section class="note"><b>用于动作观察</b><p>在线播放器支持暂停、逐帧前进（F）、当前画布导出（Shift+D）和录像设置（W）。可以先观察三个职业的姿态和攻击节奏。播放器的技能对应关系可能不完整，不应当作原游戏全部动画清单。</p><a href="https://mizagbf.github.io/GBFAP/" target="_blank" rel="noopener">播放器使用说明 ↗</a></section></main><footer>素材版权 ©Cygames, Inc. 或其许可方 · 2026-09-28 · 原素材均保留，本轮研究资料单独存放。</footer></body></html>'''
(R/'fantasy-jobs.html').write_text(page,encoding='utf-8')
link='<div style="padding:18px;background:#293444;margin:18px 0"><a href="fantasy-jobs.html">最新：日系奇幻职业 · 战士 / 法师 / 刺客 · 独立研究包 →</a></div>'
for name in ['index.html','build_collection.py','anime-learning-downloads.html','build_learning_gallery.py','nonpixel-action-candidates.html','build_nonpixel_shortlist.py']:
 p=R/name;s=p.read_text(encoding='utf-8')
 if 'href="fantasy-jobs.html"' not in s:s=s.replace('</header>',link+'</header>');p.write_text(s,encoding='utf-8')
print('3 separate fantasy job research packs and gallery created.')
